### PR TITLE
Use 4x function API when on Puppet 4

### PR DESCRIPTION
**Pull request by shanemadden**
Add a version condition to use the 4x function API when on puppet 4.

### CODE REVIEW

**Comment by rnelson0** [comment]
@shanemadden I don't use Puppet 4 yet, so I have a naive question. Is there any sort of test that would need to be/can be added for this?

**Comment by shanemadden** [comment]
@rnelson0 I'm.. actually not sure if that's doable, to test across both 3.x and 4.x. The testing procedure in an ideal world would be "run the tests against both versions".

**Comment by rnelson0** [comment]
@shanemadden I just added Travis CI to my repo but I can't figure out how to get it to run for older PRs. I'm going to close this, please submit a new PR though and I can merge it if it passes. Thanks!

**Comment by rnelson0** [comment]
@shanemadden FYI, I tried this code and it fails with:
````1) hiera_resources test1 with a notify and full message
     Failure/Error: )
       expected hiera_resources("test1") to have returned {"notify"=>{"title 1"=>{"message"=>"this is the first message stored in YAML"}}} instead of raising Puppet::ParseError(hiera_hash() has been converted to 4x API)
     # ./spec/functions/hiera_resources_spec.rb:11:in`block (2 levels) in <top (required)>'

```
I am trying to find docs on the 4x API to make this call properly.
```

**Pull request closed without merging**
